"""added many-to-many relationship for division and projects

Revision ID: 3892585feb20
Revises: d86c4425a51a
Create Date: 2023-06-30 14:08:46.828459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3892585feb20'
down_revision = 'd86c4425a51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collab_project',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['Divisions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collab_project')
    # ### end Alembic commands ###
