"""Adjusted divisions to include users

Revision ID: cbddf9486d04
Revises: 6be904da41cd
Create Date: 2023-06-30 15:27:29.802946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbddf9486d04'
down_revision = '6be904da41cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('division_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Divisions', ['division_id'], ['id'])
        batch_op.drop_column('password')
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('division_id')

    # ### end Alembic commands ###
