"""initial migration

Revision ID: d86c4425a51a
Revises: 
Create Date: 2023-06-30 13:24:21.378299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86c4425a51a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Action_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason_for_delay_comm', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Action_items', schema=None) as batch_op:
        batch_op.drop_column('reason_for_delay_comm')

    # ### end Alembic commands ###
